site_name: DoE
site_url: https://basf.github.io/doe
repo_name: DoE
repo_url: https://github.com/basf/doe

nav:
  - Overview: index.md
  - Getting started:
    - Install: install.md
    - Tutorial: tutorial.md
    - Tips: tips.md
  - Examples:
    - Large decision variable space: large_mixture.md
    - Tentative NChooseK constraint support: nchoosek_constraint.md
    - Multiple mixture constraints: multiple_mixture_constraints.md
    - Performance compared to modde: modde_comparison.md

theme:
  name: material
  repo_url: https://github.com/basf/doe
  logo: assets/logo.PNG
  favicon: assets/logo.PNG
  features:
    toc.integrate

plugins:
  - search
  - mkdocstrings:

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.highlight:
      use_pygments: true

extra_css:
  - stylesheets/style.css 

extra_javascript:
  # math support, https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  # - javascripts/mathjax.js  # when enabled, formulas come with a vertical scrollbar
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
